trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - '**/*.md'

jobs:
- job: CI
  displayName: CI Build
  timeoutInMinutes: 10
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    displayName: Checkout
  - task: UseDotNet@2
    displayName: Initialize .NET SDK
    inputs:
      packageType: sdk
      version: 5.x
  - task: PowerShell@2
    displayName: Build
    inputs:
      filePath: Auto Arknights CLI/build-winx64.ps1
      workingDirectory: Auto Arknights CLI
  - task: ArchiveFiles@2
    displayName: Archive Artifact
    inputs:
      rootFolderOrFile: Auto Arknights CLI/artifact
      includeRootFolder: false
      archiveType: 7z
      sevenZipCompression: ultra
      archiveFile: $(Build.ArtifactStagingDirectory)/Auto Arknights.7z
      replaceExistingArchive: true
  - task: PublishPipelineArtifact@1
    displayName: Publish Artifact
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)/Auto Arknights.7z
      artifactName: Auto Arknights CLI