trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - '**/*.md'

pool:
  vmImage: windows-latest

steps:
- checkout: self
  name: "Checkout"
- task: UseDotNet@2
  name: "Init"
  inputs:
    packageType: 'sdk'
    version: '5.x'
- task: PowerShell@2
  name: "Build"
  inputs:
    filePath: 'Auto Arknights CLI/build-winx64.ps1'
    workingDirectory: 'Auto Arknights CLI'
- task: PublishPipelineArtifact@1
  name: "Publish"
  inputs:
    targetPath: 'Auto Arknights CLI/artifact'
    artifactName: 'Auto-Arknights-CLI'